module.exports = {
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.js', '**/?(*.)+(spec|test).js'],
  testPathIgnorePatterns: ['/node_modules/', '/src/tests/setup.js', '/src/tests/teardown.js', '/src/tests/afterEnv.js'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@models/(.*)$': '<rootDir>/src/models/$1',
    '^@controllers/(.*)$': '<rootDir>/src/modules/$1/controllers/$1',
    '^@services/(.*)$': '<rootDir>/src/modules/$1/services/$1',
    '^@repositories/(.*)$': '<rootDir>/src/modules/$1/repositories/$1',
    '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
  },
  collectCoverageFrom: [
    'src/**/*.{js,ts}',
    '!src/**/*.d.ts',
    '!src/**/index.ts',
    '!src/database/migrations/**',
    '!src/database/seeders/**',
    '!src/tests/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coveragePathIgnorePatterns: ['/node_modules/', '/src/tests/'],
  setupFilesAfterEnv: ['<rootDir>/src/tests/afterEnv.js'],
  setupFiles: ['<rootDir>/src/tests/setup.js'],
  globalTeardown: '<rootDir>/src/tests/teardown.js',
  moduleFileExtensions: ['js', 'json', 'ts'],
  verbose: true,
};